id: P010726
initial_creation_type: ocr
source_metadata:
  id: bdr:W30417
  title: རྣམ་ཐར་པདྨའི་ཕྲེང་བ
  author: ''
  volumes:
    0f97d1b2cb774f0792f7560f105e9977:
      image_group_id: I1GS105480
      title: ''
      volume_number: 1
      total_pages: 194
