id: P010726
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30417
  title: རྣམ་ཐར་པདྨའི་ཕྲེང་བ
  author: ''
  volumes:
    0f97d1b2cb774f0792f7560f105e9977:
      image_group_id: I1GS105480
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
